---
title: "StateMap"
format: html
editor: source
---

```{r}
wd = "/Users/Hayden/Maps/"
library(dplyr)
library(readxl)
library(usmap)
library(sf)
library(tigris)
```

# This code expands on the usmap package's state_map to create the one I use for mapping

```{r}
#To do: add PR population data

state_map = us_map("states") |>
  rename(geometry = geom,
         name = full)

pr <- states("PR", resolution = "20m", cb = TRUE, year = 2020) |>
  filter(STATEFP == 72) |>
  mutate(fips = "72",
         abbr = "PR",
         name = "Puerto Rico") |>
  select(fips, abbr, name)
  
  pr <- st_transform(pr, 4326)
  
  st_geometry(pr) <- st_geometry(pr) + c(-11, 13) #Shift PR to be off the coast of Georgia
  st_crs(pr) <- 4326 # Restore CRS (lost after shifting)
  pr <- st_transform(pr, usmap_crs())
  
  state_map = rbind(state_map, pr)

state_map <- state_map |>
  mutate(centroid = st_centroid(geometry),
         x = st_coordinates(centroid)[, 1], # Longitude
         y = st_coordinates(centroid)[, 2] # Latitude
         )

adjustments <- tibble::tibble(
  abbr = c("CA", "NJ", "MI", "MD", "LA", "FL", "HI", "ID", "WV", "ME", "VA"), #adjust centroids
  x_adj = c(-40000, 10000,80000, -25000, -0,80000, 80000, 0, -20000, 20000, 30000),
  y_adj = c(0, 0,-100000, 35000, -40000,0,-70000, -50000, 0, 0, 0)
)

state_map <- state_map |>
  left_join(adjustments, by = "abbr") |>
  mutate(
    x = coalesce(x + x_adj, x),  # Apply adjustment if exists, otherwise keep original
    y = coalesce(y + y_adj, y)
  ) |>
  select(-x_adj, -y_adj)


state_pops = read_csv("https://raw.githubusercontent.com/JoshData/historical-state-population-csv/refs/heads/primary/historical_state_population_by_year.csv")

colnames(state_pops) = c("abbr", "year", "pop")

state_pops <- state_pops |>
  filter(year > 1999) |> #probably won't need anything earlier
  mutate(pop_name = paste0("pop",sprintf("%02d", year-2000))) |>
  select(-year) |>
  pivot_wider(names_from = pop_name, values_from = pop)

state_map = left_join(state_map, state_pops, by = "abbr") |>
  mutate(pop = pop20)

state_areas = read_csv("https://raw.githubusercontent.com/jakevdp/data-USstates/refs/heads/master/state-areas.csv")

colnames(state_areas) = c("name", "sqmi")

state_map = left_join(state_map, state_areas)
```

#Save state_map

```{r}
#st_write(state_map, "state_map/state_map.shp", delete_dsn = TRUE)
```

```{r}
data = state_map |>
  st_drop_geometry() |>
  mutate(Value = runif(n = nrow(state_map))) |>
  select(Value, fips)

map(data = data,
  map = state_map,
  state_map = state_map,
  bubbles = F,
  continental = F,
  title = "State Map Test",
  source = ""
)
```
