---
title: "Test_Maps"
format: pdf
editor: source
---

This file is for testing the mapping function found in MappingFunction.qmd using the map shapefiles constructed in Construct_Maps.qmd.

#sample_data
```{r}
sample_data <- function(map, dist = "unif") {
  sample_data = map |>
    st_drop_geometry() |>
    mutate(Value = case_when(dist == "unif" ~ runif(n = nrow(map)),
                             dist == "norm" ~ rnorm(n = nrow(map)),
                             T ~ 1) ) |>
    select(Value, fips)
  return(sample_data)
}
```


#County Maps

```{r}
county_sample_data = sample_data(county_map)

map(data = county_sample_data,
  state_map = state_map_largepr,
  map = county_map,
  bubbles = F,
  title = "County Map Test",
  unit = "%",
  source = "",
  caption_manual = "Test caption",
  inset_style = "split"
)

map(data = county_sample_data,
  state_map = state_map_largepr,
  map = county_map,
  bubbles = F,
  continental = T,
  title = "County Map Test (Continental)",
  unit = "%",
  source = "",
  caption_manual = "Test caption",
  inset_style = "split"
)

county_sample_data = sample_data(county_map, dist = "norm")

#bubble map test
map(data = county_sample_data,
  state_map = state_map_largepr,
  map = county_map,
  bubbles = T,
  title = "County Map Test",
  source = "",
  scale_center = 0,
  caption_manual = "Test caption",
  inset_style = "split"
)
```


#State Maps

```{r}
state_sample_data = sample_data(state_map)

map(data = state_sample_data,
  map = state_map,
  state_map = state_map,
  bubbles = F,
  title = "State Map Test",
  unit = "%",
  source = "",
  caption_manual = "Test caption",
  inset_style = "split"
)

map(data = state_sample_data,
  map = state_map,
  state_map = state_map,
  bubbles = F,
  continental = T,
  title = "State Map Test (Continental)",
  unit = "%",
  source = "",
  caption_manual = "Test caption",
  inset_style = "split"
)
```


#North America Map

```{r}
#might want to move PR up or SouthWest to not collide with inset for this one
na_sample_data = sample_data(na_map)

map(data = na_sample_data,
  map = na_map,
  state_map = na_map,
  bubbles = F,
  title = "North America Map Test",
  unit = "%",
  source = "",
  caption_manual = "Test caption",
  inset_style = "split"
)
```


#PUMA Map

```{r}
puma_sample_data = sample_data(puma_map)

map(data = puma_sample_data,
  state_map = state_map_largepr,
  map = puma_map,
  bubbles = F,
  title = "PUMA Map Test",
  unit = "%",
  source = "",
  caption_manual = "Test caption",
  inset_style = "split"
)
```


#MSA Map

```{r}
#might do later
```


#ZIP Map

```{r}
#will do later
```

